name: "Pull Request Labeler"
on:
- pull_request

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v6
      id: labeler
      with:
        sync-labels: true
    - env:
        ALL_LABELS: ${{ steps.labeler.outputs.all-labels }}
      run: |
        echo "Labels: ${ALL_LABELS}"
